pluginManagement {
	repositories {
		gradlePluginPortal()
		mavenCentral()
	}
}

plugins {
	id 'com.gradle.develocity' version '4.5.0'
}

rootProject.name = "hibernate-accessor-group"

dependencyResolutionManagement {
	repositories {
		mavenCentral()
		if (rootProject.hasProperty("enableSnapshotRepositories")) {
			maven {
				// temporary - Maven Central snapshots repo for ORM snapshots
				url = "https://central.sonatype.com/repository/maven-snapshots/"
				mavenContent {
					snapshotsOnly()
				}
			}
		}
		// Needed for RC versions of Jakarta Persistence
		maven {
			url = "https://jakarta.oss.sonatype.org/content/repositories/releases/"
		}
		// Needed for Beta versions of Jakarta Persistence
		maven {
			url = "https://jakarta.oss.sonatype.org/content/groups/staging/"
		}
		if (rootProject.hasProperty("enableSnapshotRepositories")) {
			// Needed for SNAPSHOT versions of Jakarta Persistence (wtf)
			maven {
				url = "https://jakarta.oss.sonatype.org/content/repositories/snapshots/"
			}
		}
	}
}

develocity {
	server = 'https://develocity.commonhaus.dev'

	buildScan {
		capture {
			fileFingerprints = true
		}
		publishing.onlyIf { it.authenticated }

		obfuscation {
			// Don't share ip addresses
			ipAddresses { addresses -> addresses.collect { address -> "0.0.0.0" } }
		}

//			uploadInBackground = !settings.ext.isCiEnvironment
//
//			tag "jdk-${settings.extensions.jdkVersions.test.launcher}"
//			tag settings.extensions.db
//			value 'database', settings.extensions.db
//
//			if ( settings.extensions.findByName( 'ci.node' ) ) {
//				tag settings.extensions.findByName( 'ci.node' )
//			}
	}
}

include 'reporting'

include 'hibernate-accessor-benchmark-basic'
project(':hibernate-accessor-benchmark-basic').projectDir = file( 'performance/benchmark-basic' )
include 'hibernate-accessor-benchmark-model-generator'
project(':hibernate-accessor-benchmark-model-generator').projectDir = file( 'performance/benchmark-model/generator' )
include 'hibernate-accessor-benchmark-model'
project(':hibernate-accessor-benchmark-model').projectDir = file( 'performance/benchmark-model/benchmarks' )

include 'hibernate-accessor'
include 'hibernate-accessor-asm'
include 'hibernate-accessor-bytebuddy'
include 'hibernate-accessor-bom'

include 'hibernate-accessor-tck'
project(':hibernate-accessor-tck').projectDir = file( 'testing/hibernate-accessor-tck' )
include 'hibernate-accessor-tck-reflection'
project(':hibernate-accessor-tck-reflection').projectDir = file( 'testing/hibernate-accessor-tck-reflection' )
include 'hibernate-accessor-tck-methodhandle'
project(':hibernate-accessor-tck-methodhandle').projectDir = file( 'testing/hibernate-accessor-tck-methodhandle' )
include 'hibernate-accessor-tck-lambda'
project(':hibernate-accessor-tck-lambda').projectDir = file( 'testing/hibernate-accessor-tck-lambda' )
include 'hibernate-accessor-tck-asm'
project(':hibernate-accessor-tck-asm').projectDir = file( 'testing/hibernate-accessor-tck-asm' )
include 'hibernate-accessor-tck-bytebuddy'
project(':hibernate-accessor-tck-bytebuddy').projectDir = file( 'testing/hibernate-accessor-tck-bytebuddy' )

include 'hibernate-accessor-tck-jpms-entities'
project(':hibernate-accessor-tck-jpms-entities').projectDir = file( 'testing/hibernate-accessor-tck-jpms-entities' )
include 'hibernate-accessor-tck-jpms'
project(':hibernate-accessor-tck-jpms').projectDir = file( 'testing/hibernate-accessor-tck-jpms' )
