[versions]
# libs
byteBuddy = "1.18.12"
ow2Asm = "9.10.1"
jbossLogging = "3.6.3.Final"
jbossLoggingTool = "3.0.4.Final"
jmh = "1.37"

# jdks
jdks-baseline = "17"

# testLibs
assertj = "3.27.7"
junitJupiter = "6.1.3"
junitPlatformJupiter= "6.1.3"
log4j = "2.26.1"

# plugins
spotless="8.10.1"
develocity="4.5.0"

[libraries]
# libs
byteBuddy = { group = "net.bytebuddy", name = "byte-buddy", version.ref = "byteBuddy" }
byteBuddyAgent = { group = "net.bytebuddy", name = "byte-buddy-agent", version.ref = "byteBuddy" }
asm = { group = "org.ow2.asm", name = "asm", version.ref = "ow2Asm" }
jmh-core = { group = "org.openjdk.jmh", name = "jmh-core", version.ref = "jmh" }
jmh-generatorAnnprocess = { group = "org.openjdk.jmh", name = "jmh-generator-annprocess", version.ref = "jmh" }
loggingCore = { group = "org.jboss.logging", name = "jboss-logging", version.ref = "jbossLogging" }
loggingAnnotations = { group = "org.jboss.logging", name = "jboss-logging-annotations", version.ref = "jbossLoggingTool" }
loggingProcessor = { group = "org.jboss.logging", name = "jboss-logging-processor", version.ref = "jbossLoggingTool" }

# testLibs
test-assertjCore = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
test-junitJupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitJupiter" }
test-junitJupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiter" }
test-junitJupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitJupiter" }
test-junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitPlatformJupiter" }
test-junitPlatformSuiteEngine = { group = "org.junit.platform", name = "junit-platform-suite-engine", version.ref = "junitPlatformJupiter" }
test-log4jCore = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
develocity = { id = "com.gradle.develocity", version.ref = "develocity" }
